arch: amd64
os: linux
dist: focal

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

install: 
  - pip install sanic
  - pip install fastapi
  - pip install pytest

stages:
  - test
jobs:
  include:
    - test:
      script: 
        - pytest tests/