name: Pytest

on:
  push:
    branches:
      - nightly
      - staging
  pull_request:
    branches: 
      - nightly
      - staging

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.7, 3.8, 3.9]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-versions }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade pytest
    - name: Running Unit Tests
      run: |
        pytest tests/